### ISSUE TITLE
All Files Gone

### ISSUE THREAD

**Issue by theWebKeyGuy** [iamshaunjp/websockets-playlist#11]
Hello, so I went to look for our repo from the second you created on websockets and theres no css here for the project. I don't mind making my own but when you say in your video to go to the link and get it and its not there its quite upsetting.

**Comment by ankit1738** [comment]
theWebKeyGuy, Mate you wanna go to lesson 2 to view the css

**Comment by fromage9747** [comment]
@theWebKeyGuy If you didn't understand @ankit1738, please follow the below screenshots.

On first navigation of this repo:

![selection_007](https://user-images.githubusercontent.com/23147783/38774447-a019cb44-4093-11e8-88ab-c8f6b200d844.png)

Click on branch master and select lesson 2 as per @ankit1738 

![selection_008](https://user-images.githubusercontent.com/23147783/38774454-c13136be-4093-11e8-8c19-e7913e59d677.png)

If you are coming here to get the css then click on public:

![selection_009](https://user-images.githubusercontent.com/23147783/38774457-d61caa9a-4093-11e8-9895-baf2cd8eaef6.png)

Then click on styles.css

![selection_010](https://user-images.githubusercontent.com/23147783/38774459-df7a9fd4-4093-11e8-916c-b273084ddcdf.png)

And there you go, the css for you to copy and paste:

![selection_011](https://user-images.githubusercontent.com/23147783/38774462-e93063ec-4093-11e8-871d-e4610b7b9783.png)

Simple! Cheers

**Comment by fivestones** [comment]
Thanks. I thought all the files were missing too!
