### ISSUE TITLE
Reg. keypress for "Typing" event

### ISSUE THREAD

**Issue by naman1303** [iamshaunjp/websockets-playlist#17]
As per your YouTube video, single "XYZ is typing a message.. " comes for whole sentence (including words and spaces), until you click on the button.

But when I run my program, every single keystroke is leading to "XYZ is typing a message.. ", which seems correct behaviour of "keypress". 

What did you do to avoid this?

**Comment by rishav394** [comment]
You are probably appending it to the div tag. Try replacing instead of appending.

**Comment by naman1303** [comment]
My bad. Yes I was appending it by mistake. Working after correction. Thanks.
